### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by steve22184** [c3re/can2mqtt#14] opened 2019-07-07 11:11 UTC
I try running on raspberry pi and I got an error:

mqtthandler: Oh no an error occured...
panic: Not Authorised

goruntime 1 [running]:
github.comc3re/can2mqtt.mqttStart(0x29fa8a, 0x14)
/home/openhabian/go_projects/src/github.com/c3re/can2mqtt/mqtthandling.go:22 +0x35c
github.com/c3re/can2mqtt.Start()
/home/openhabian/go_projects/src/github.com/c3re/can2mqtt/main.go:66 +0x6c
main.main()
/home/openhabian/go_projects/src/github.com/c3re/can2mqtt/can2mqtt/main.go:33 +0x298

**Comment by mxmxchere** [comment] 2019-10-16 20:10
Hi,

what was the command that you executed e.g. which parameters did you provide to can2mqtt?

**Comment by mxmxchere** [comment] 2020-12-23 10:30
Without further information it is hard to debug that issue. I assume there has been an authentication issue with the mqtt broker. I am going to close this issue. Feel free to reopen and to provide more details.

**Closed by mxmxchere** 2020-12-23 10:30 UTC

**Comment by mxmxchere** [comment] 2022-06-11 07:16
Hi @steve22184 i guess this issue was caused by an mqtt-server that required authentication. Now its possible to authenticate to a server if you use tcp://user:pass@server:1883 as your connect-string.

Best
Malte
